# PyTorch Tensors

Tensors are the fundamental data structure used by PyTorch.
They are similar to NumPy arrays, but they are designed for deep learning and can run on GPUs.

In this notebook, we will explore:

- Tensor creation
- Tensor dimensions
- Tensor shapes
- Tensor data types
- Tensor conversion
- NumPy and PyTorch interoperability
- Creating tensors filled with zeros and ones
- Creating sequences with `torch.arange()`

In [1]:
import torch
import numpy as np

print("PyTorch Version:", torch.__version__)

PyTorch Version: 2.12.1+cpu


## 1. Tensor Creation

PyTorch tensors can represent data with different numbers of dimensions.
A scalar contains a single value, a vector contains a sequence of values, and matrices and higher-dimensional tensors contain multiple dimensions.

In [2]:
scalar = torch.tensor(7)

vector = torch.tensor([1, 2, 3, 4])

matrix = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

tensor_3d = torch.tensor([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

# Results
print("Scalar:")
print(scalar)

print("\nVector:")
print(vector)

print("\nMatrix:")
print(matrix)

print("\n3D Tensor:")
print(tensor_3d)

Scalar:
tensor(7)

Vector:
tensor([1, 2, 3, 4])

Matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])

3D Tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


## 2. Tensor Dimensions

The `ndim` property tells us how many dimensions a tensor has.

- Scalar → 0 dimensions
- Vector → 1 dimension
- Matrix → 2 dimensions
- 3D Tensor → 3 dimensions

In [3]:
print("Scalar dimensions:", scalar.ndim)
print("Vector dimensions:", vector.ndim)
print("Matrix dimensions:", matrix.ndim)
print("3D Tensor dimensions:", tensor_3d.ndim)

Scalar dimensions: 0
Vector dimensions: 1
Matrix dimensions: 2
3D Tensor dimensions: 3


## 3. Tensor Shapes

The `shape` property tells us the size of each dimension of a tensor.
For example, a matrix containing 2 rows and 3 columns has a shape of `(2, 3)`.

In [4]:
print("Scalar shape:", scalar.shape)
print("Vector shape:", vector.shape)
print("Matrix shape:", matrix.shape)
print("3D Tensor shape:", tensor_3d.shape)

Scalar shape: torch.Size([])
Vector shape: torch.Size([4])
Matrix shape: torch.Size([2, 3])
3D Tensor shape: torch.Size([2, 2, 2])


## 4. Tensor Data Types

Every PyTorch tensor has a data type.
The `dtype` attribute tells us the type of values stored inside the tensor.
We can also explicitly specify a data type when creating a tensor.

In [6]:
integer_tensor = torch.tensor([1, 2, 3, 4])
float_tensor = torch.tensor([1.0, 2.0, 3.0, 4.0])
float32_tensor = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
int64_tensor = torch.tensor([1, 2, 3, 4], dtype=torch.int64)

print("Integer Tensor:", integer_tensor)
print("Data Type:", integer_tensor.dtype)

print("\nFloat Tensor:", float_tensor)
print("Data Type:", float_tensor.dtype)

print("\nFloat32 Tensor:", float32_tensor)
print("Data Type:", float32_tensor.dtype)

print("\nInt64 Tensor:", int64_tensor)
print("Data Type:", int64_tensor.dtype)

Integer Tensor: tensor([1, 2, 3, 4])
Data Type: torch.int64

Float Tensor: tensor([1., 2., 3., 4.])
Data Type: torch.float32

Float32 Tensor: tensor([1., 2., 3., 4.])
Data Type: torch.float32

Int64 Tensor: tensor([1, 2, 3, 4])
Data Type: torch.int64


## 5. Tensor Conversion

Tensor data types can be converted when needed.
For example, an integer tensor can be converted into a floating-point tensor using `.float()`.

In [7]:
tensor = torch.tensor([1, 2, 3, 4])

print("Original Tensor:")
print(tensor)
print("Original Data Type:", tensor.dtype)

float_tensor = tensor.float()

print("\nConverted Tensor:")
print(float_tensor)
print("Converted Data Type:", float_tensor.dtype)

int_tensor = float_tensor.int()

print("\nConverted Back to Integer:")
print(int_tensor)
print("Data Type:", int_tensor.dtype)

Original Tensor:
tensor([1, 2, 3, 4])
Original Data Type: torch.int64

Converted Tensor:
tensor([1., 2., 3., 4.])
Converted Data Type: torch.float32

Converted Back to Integer:
tensor([1, 2, 3, 4], dtype=torch.int32)
Data Type: torch.int32


## 6. NumPy and PyTorch

PyTorch provides tools for working with NumPy arrays.
`torch.from_numpy()` can convert a NumPy array into a PyTorch tensor.
The resulting tensor shares memory with the original NumPy array, so modifying the NumPy array can also modify the tensor.

In [8]:
numpy_array = np.array([10, 20, 30, 40, 50])
tensor = torch.from_numpy(numpy_array)

print("NumPy Array:")
print(numpy_array)

print("\nPyTorch Tensor:")
print(tensor)

numpy_array[0] = 100

print("\nAfter modifying NumPy Array:")
print("NumPy Array:", numpy_array)
print("PyTorch Tensor:", tensor)

NumPy Array:
[10 20 30 40 50]

PyTorch Tensor:
tensor([10, 20, 30, 40, 50])

After modifying NumPy Array:
NumPy Array: [100  20  30  40  50]
PyTorch Tensor: tensor([100,  20,  30,  40,  50])


## 7. Zeros and Ones

PyTorch provides convenient functions for creating tensors filled with zeros or ones.
`torch.zeros()` creates a tensor containing only zeros.
`torch.ones()` creates a tensor containing only ones.

In [9]:
zeros_tensor = torch.zeros(3, 4)
ones_tensor = torch.ones(3, 4)

print("Zeros Tensor:")
print(zeros_tensor)

print("\nOnes Tensor:")
print(ones_tensor)

print("\nZeros Tensor Shape:", zeros_tensor.shape)
print("Ones Tensor Shape:", ones_tensor.shape)

Zeros Tensor:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Ones Tensor:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Zeros Tensor Shape: torch.Size([3, 4])
Ones Tensor Shape: torch.Size([3, 4])


## 8. Creating Sequences with `torch.arange()`

`torch.arange()` creates a tensor containing values within a specified range.

The basic form is:

`torch.arange(start, end, step)`

The end value is excluded from the generated sequence.

In [10]:
tensor = torch.arange(0, 10)

print("Tensor:")
print(tensor)

print("\nShape:", tensor.shape)
print("Data Type:", tensor.dtype)
print("Number of Elements:", tensor.numel())

Tensor:
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Shape: torch.Size([10])
Data Type: torch.int64
Number of Elements: 10


## 9. Tensor Overview

The examples above demonstrate the basic building blocks of working with tensors in PyTorch.
We created tensors, inspected their dimensions and shapes, worked with different data types, converted tensors, connected NumPy with PyTorch, created predefined tensors, and generated numerical sequences.

In [11]:
example = torch.tensor([[10.0, 20.0, 30.0],
                        [40.0, 50.0, 60.0]])

print("Tensor:")
print(example)

print("\nDimensions:", example.ndim)
print("Shape:", example.shape)
print("Data Type:", example.dtype)
print("Number of Elements:", example.numel())

Tensor:
tensor([[10., 20., 30.],
        [40., 50., 60.]])

Dimensions: 2
Shape: torch.Size([2, 3])
Data Type: torch.float32
Number of Elements: 6


## Key Takeaways

- Tensors are the core data structure of PyTorch.
- `ndim` tells us the number of dimensions.
- `shape` tells us the size of each dimension.
- `dtype` tells us the data type of tensor values.
- `.float()` and `.int()` can convert tensor data types.
- `torch.from_numpy()` connects NumPy arrays with PyTorch tensors.
- `torch.zeros()` and `torch.ones()` create predefined tensors.
- `torch.arange()` creates numerical sequences.

> **Next Section:** Autograd