In [3]:
import numpy as np

# Scalar Array
array1 = np.array([1, 2, 3, 4])

print(array1 + 1)
print(array1 - 2)
print(array1 * 3)
print(array1 / 4)
print(array1 ** 5)

[2 3 4 5]
[-1  0  1  2]
[ 3  6  9 12]
[0.25 0.5  0.75 1.  ]
[   1   32  243 1024]


In [8]:
# Vector Math Functions
array1 = np.array([9.9867, 6.0998, 2.1125])

print(np.sqrt(array1))
print(np.round(array1))
print(np.floor(array1))
print(np.ceil(array1))
print(np.pi)

[3.16017405 2.46977732 1.45344419]
[10.  6.  2.]
[9. 6. 2.]
[10.  7.  3.]
3.141592653589793


In [10]:
radii = np.array([1, 2, 3])
print(np.pi*(radii ** 2))

[ 3.14159265 12.56637061 28.27433388]


In [20]:
# Element-wise Arithmetic

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [21]:
# Comparison Operators
scores = np.array([23, 76, 89, 61, 100, 14, 69, 95])

In [22]:
print(scores == 100)

[False False False False  True False False False]


In [23]:
print(scores >=60 )

[False  True  True  True  True False  True  True]


In [25]:
scores[scores < 60] = 0
print(scores)

[  0  76  89  61 100   0  69  95]


In [27]:
# Final >_<
import numpy as np

array = np.array([1, 2, 3])

print("Original Array    :", array)
print("Squared Values    :", array ** 2)
print("Cubed Values      :", array ** 3)
print("Square Root       :", np.sqrt(array))

print()

print("Sine Values       :", np.sin(array))
print("Cosine Values     :", np.cos(array))
print("Exponential       :", np.exp(array))
print("Natural Log       :", np.log(array))


Original Array    : [1 2 3]
Squared Values    : [1 4 9]
Cubed Values      : [ 1  8 27]
Square Root       : [1.         1.41421356 1.73205081]

Sine Values       : [0.84147098 0.90929743 0.14112001]
Cosine Values     : [ 0.54030231 -0.41614684 -0.9899925 ]
Exponential       : [ 2.71828183  7.3890561  20.08553692]
Natural Log       : [0.         0.69314718 1.09861229]
