In [2]:
import numpy as np

scores = np.array([72, 85, 91, 63, 78, 55, 99, 81])

print("Mean                :", np.mean(scores))
print("Median              :", np.median(scores))
print("Standard Deviation  :", np.std(scores))
print("Variance            :", np.var(scores))
print("Minimum Score       :", np.min(scores))
print("Maximum Score       :", np.max(scores))
print("25th Percentile     :", np.percentile(scores, 25))
print("75th Percentile     :", np.percentile(scores, 75))

Mean                : 78.0
Median              : 79.5
Standard Deviation  : 13.5
Variance            : 182.25
Minimum Score       : 55
Maximum Score       : 99
25th Percentile     : 69.75
75th Percentile     : 86.5


In [3]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(np.sum(matrix, axis=0))
print(np.sum(matrix, axis=1))

print(np.mean(matrix, axis=0))
print(np.mean(matrix, axis=1))

[12 15 18]
[ 6 15 24]
[4. 5. 6.]
[2. 5. 8.]


In [4]:
print(f"Lowest Three       : {np.sort(scores)[:3]}")
print(f"Highest Three      : {np.sort(scores)[-3:]}")

Lowest Three       : [55 63 72]
Highest Three      : [85 91 99]
