In [8]:
import numpy as np

# Array Slicing 
# array[start:end:steps]

array1 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
print(array1)
print(array1.ndim,'Dimension')
print(array1.shape)
print(type(array1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
2 Dimension
(4, 4)
<class 'numpy.ndarray'>


In [16]:
print(array1[::1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [17]:
print(array1[::-1])

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [18]:
print(array1[0:4:2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [22]:
print(array1[0:4:3])

[[ 1  2  3  4]
 [13 14 15 16]]


In [19]:
print(array1[0:2:])

[[1 2 3 4]
 [5 6 7 8]]


In [20]:
print(array1[2:4:])

[[ 9 10 11 12]
 [13 14 15 16]]


In [49]:
# Rows and Columns (Array Slicing)

print(array1[0:2:,0:2:])  # Upper Left Quadrants of Matrix

[[1 2]
 [5 6]]


In [50]:
print(array1[0:2:,2::])  # Upper Right Quadrants of Matrix

[[3 4]
 [7 8]]


In [51]:
print(array1[2::,:2:])  # Lower Left Quadrants of Matrix

[[ 9 10]
 [13 14]]


In [52]:
print(array1[2::,2::])  # Lower Right Quadrants of Matrix

[[11 12]
 [15 16]]


In [53]:
print(array1[1:3:,1:3:])  # Center of Matrix of Matrix

[[ 6  7]
 [10 11]]


In [54]:
print(array1[0:1:,0:1:])

[[1]]


In [55]:
print(array1[3:4:,3:4:])

[[16]]
