In [1]:
import numpy as np

a = np.zeros(3)
a

array([0., 0., 0.])

In [2]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
a = np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [4]:
a.shape

(10,)

In [5]:
z_array = np.zeros(10)
print(z_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
z_array.shape

(10,)

In [37]:
# Arrays

array1 = np.array('A')
print(array1)



A


In [47]:
array1 = np.array('A')
print(array1)
print(array1.ndim,'Dimension')


A
0 Dimension


In [48]:
array1 = np.array(['A', 'B', 'C', 'D'])
print(array1)
print(array1.ndim,'Dimension')

['A' 'B' 'C' 'D']
1 Dimension


In [49]:
array1 = np.array([['A', 'B', 'C', 'D'],
                   ['E', 'F', 'G', 'H'],
                   ['I', 'J', 'K', 'L']])
print(array1)
print(array1.ndim,'Dimension')

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']
 ['I' 'J' 'K' 'L']]
2 Dimension


In [50]:
array1 = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                   [['J','K','L'],['M','N','O'],['P','Q','R']],
                   [['S','T','U'],['V','W','X'],['Y','Z',' ']]])
print(array1)
print(array1.ndim,'Dimension')

[[['A' 'B' 'C']
  ['D' 'E' 'F']
  ['G' 'H' 'I']]

 [['J' 'K' 'L']
  ['M' 'N' 'O']
  ['P' 'Q' 'R']]

 [['S' 'T' 'U']
  ['V' 'W' 'X']
  ['Y' 'Z' ' ']]]
3 Dimension


In [51]:
print(type(array1))

<class 'numpy.ndarray'>


In [52]:
array2 = np.array([1, 2, 3, 4])

print(array2)
print(array2.ndim,'Dimension')
print(array2.shape)
print(type(array2))


[1 2 3 4]
1 Dimension
(4,)
<class 'numpy.ndarray'>


In [53]:
a_list = [1, 2, 3, 4, 5, 6 ,7]
z = np.array([a_list])
z 

array([[1, 2, 3, 4, 5, 6, 7]])

In [54]:
z.shape

(1, 7)

In [55]:
type(z)

numpy.ndarray