In [3]:
import numpy as np

numbers = np.arange(1, 13)

print("Original Array:")
print(numbers)
print("Shape:", numbers.shape)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)


In [12]:
# Reshape (1D → 2D)
matrix = numbers.reshape(3, 4)

print(matrix)
print("Shape:", matrix.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


In [13]:
# Different Shapes

print(numbers.reshape(2, 6))
print()
print(numbers.reshape(4, 3))
print()
print(numbers.reshape(6, 2))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [14]:
# Automatic Dimension (-1)

print(numbers.reshape(3, -1))
print()
print(numbers.reshape(-1, 4))
print()
print(numbers.reshape(-1, 2))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [15]:
# Squeeze
array = np.array([[[1],[2],[3]]])

print(array.shape)
print(np.squeeze(array))
print(np.squeeze(array).shape)

(1, 3, 1)
[1 2 3]
(3,)


In [19]:
numbers = np.arange(1, 25)

print("Original Shape :", numbers.shape)

matrix = numbers.reshape(4, 6)
print()

print("Original Matrix:")
print(matrix)
print()

print("Transpose:")
print(matrix.T)
print()

print("Flatten:")
print(matrix.flatten())
print()

print("Reshape: (2,12)")
print(numbers.reshape(2,12))
print()

print("Reshape: (3,8)")
print(numbers.reshape(3,8))

Original Shape : (24,)

Original Matrix:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

Transpose:
[[ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]
 [ 6 12 18 24]]

Flatten:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

Reshape: (2,12)
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]

Reshape: (3,8)
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
